# -*- coding: utf-8 -*-
"""
    Constants
    :copyright: © 2018 by Nuno Gonçalves
    :license: MIT, see LICENSE for more details.
"""

from os import environ, name

IS_NT = name == "nt"
KEEPER_HOME = environ["KEEPER_HOME"]
STATUS_RUNNING = "Running"
STATUS_NOT_RUNNING = "Not Running"
TIME_FORMAT = "%Y-%m-%d %H:%M:%S"
CONNECTOR_CONNECTION_OK = "Stable"
CONNECTOR_CONNECTION_NOK = "Not Stable"
CONNECTOR_STATUS = "connectorStatus"
CONNECTOR_STATUS_ICON = "mdi:access-point"
CONNECTOR_STATUS_NAME = "Connector"
CONNECTOR_CONNECTION_STATUS = "mqttConnectionStatus"
CONNECTOR_CONNECTION_STATUS_ICON = "mdi:network"
CONNECTOR_CONNECTION_STATUS_NAME = "MQTT Connection Status"
CONNECTOR_FAILED_CONNECTIONS = "mqttFailedConnections"
CONNECTOR_FAILED_CONNECTIONS_ICON = "mdi:sync-alert"
CONNECTOR_FAILED_CONNECTIONS_NAME = "Failed MQTT Connections"
CONNECTOR_MQTT_RESTARTS = "mqttRestarts"
CONNECTOR_MQTT_RESTARTS_ICON = "mdi:restart"
CONNECTOR_MQTT_RESTARTS_NAME = "MQTT Restarts"
CONNECTOR_LAST_MQTT_RESTART = "lastMqttRestart"
CONNECTOR_LAST_MQTT_RESTART_ICON = "mdi:calendar-clock"
CONNECTOR_LAST_MQTT_RESTART_NAME = "Last MQTT Restart"
HEARTBEATER_STATUS = "heartbeaterStatus"
HEARTBEATER_STATUS_ICON = "mdi:heart-pulse"
HEARTBEATER_STATUS_NAME = "Heartbeater"
HEARTBEATER_MISSED_HEARTBEAT = "missedHeartbeat"
HEARTBEATER_MISSED_HEARTBEAT_ICON = "mdi:pipe-leak"
HEARTBEATER_MISSED_HEARTBEAT_NAME = "Missed Heartbeats"
HEARTBEATER_HA_RESTARTS = "HARestarts"
HEARTBEATER_HA_RESTARTS_ICON = "mdi:restart"
HEARTBEATER_HA_RESTARTS_NAME = "HA Restarts"
HEARTBEATER_LAST_HA_RESTART = "lastHARestart"
HEARTBEATER_LAST_HA_RESTART_ICON = "mdi:calendar-clock"
HEARTBEATER_LAST_HA_RESTART_NAME = "Last HA Restart"
HEARTBEATER_SYSTEM_RESTARTS = "systemRestarts"
HEARTBEATER_SYSTEM_RESTARTS_ICON = "mdi:server"
HEARTBEATER_SYSTEM_RESTARTS_NAME = "System Restarts"
HEARTBEATER_LAST_SYSTEM_RESTART = "lastSystemRestart"
HEARTBEATER_LAST_SYSTEM_RESTART_ICON = "mdi:calendar-clock"
HEARTBEATER_LAST_SYSTEM_RESTART_NAME = "Last System Restart"
HEARTBEATER_LAST_HEARTBEAT = "lastHeartbeat"
HEARTBEATER_LAST_HEARTBEAT_ICON = "mdi:calendar-clock"
HEARTBEATER_LAST_HEARTBEAT_NAME = "Last Heartbeat"
STATE_TOPIC = "homeassistant/sensor/kp%s/state"
CONFIG_TOPIC = "homeassistant/sensor/kp%s/config"
CONFIG_PAYLOAD = "{\"name\": \"%s\", \"state_topic\": \"" + STATE_TOPIC + "\", \"icon\": \"%s\"}"
